### ISSUE TITLE
KSW1850

### ISSUE THREAD

**Issue by DavidHaslam** [digitalbiblesociety/Archive-Bibles#2]
I see that you used **CrossWire** as the source for the data in **KSW1850**. 

As such CrossWire PD source text projects are hosted on GitLab and your Bible Archive is hosted on GitHub, how will you ensure that subsequent changes made by CrossWire will be synchronised here?

cf. I made some changes earlier today to the **sgawkaren** project. 

Aside: Why KSW1850 rather than KSW1853 as the directory name?

**Comment by jonBitgood** [comment]
I've added a star the sgaw karen bible on gitlab. We'll be doing our best to stay current across both platforms. The reason 1850 was chosen was because [this historic scan](https://archive.org/details/TheNewTestamentBookOfMatthewInKaren-BurmaMyanmarIndia1850) referred to the resource with a publication date of 1850.

**Comment by DavidHaslam** [comment]
Ah - but that’s only the Gospel of Matthew - the first NT book he translated. 

cf. It’s customary to use the year for when a complete NT was published as the edition date. 

The S’gaw Karen project on GitLab is for the complete Bible.
